### ISSUE TITLE
low map,test you provide weights,can you provide test scripts?

### ISSUE THREAD

**Issue by 92ypli** [westerndigitalcorporation/YOLOv3-in-PyTorch#1]
![image](https://user-images.githubusercontent.com/22673185/69239378-03540900-0bd5-11ea-9007-04078219241c.png)

**Comment by wuhy08** [comment]
Hi @92ypli 

What confidence threshold are you using. The default value for confidence threshold is 0.8. I recommend using 0.4 or 0.5 as a starting point. In the `python3 main.py test ...` script, use option `--conf-thres 0.5` and try again.

**Comment by 92ypli** [comment]
Thanks you, i get it. and can you provide pretrained weight?not trained well weights.

**Comment by wuhy08** [comment]
Hi @92ypli 

Did you try the weights provided by the repo? See https://github.com/westerndigitalcorporation/YOLOv3-in-PyTorch/raw/release/weights/yolov3_original.pt

**Comment by ElectronicElephant** [comment]
> Hi @92ypli
> 
> What confidence threshold are you using. The default value for confidence threshold is 0.8. I recommend using 0.4 or 0.5 as a starting point. In the `python3 main.py test ...` script, use option `--conf-thres 0.5` and try again.

Hi, thanks for your great work!

I'm quite new to the area of Object Detection and have some questions about the value of the conf-thres.

Definitely, lowering the value of the threshold will boost the mAP. In my case, if the threshold is lowered to `0.001`, with `yolov3_origin.pt` and `data-shape=416`, I can get a really high mAP(0.5:0.95) of `36.4`, which is comparable to the `gluon-cv` implementation.

```
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.364
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.647
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.374
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.189
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.400
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.538
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.294
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.445
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.469
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.277
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.511
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.638
```

I'm quite sure that `gluon-cv` is also using `0.001` ,or `0.05`, which doesn't affect much, as the threshold. Someone also said that the original `darknet c++` use `0.005`. However, many papers just don't report the threshold. My question is, when people reporting the mAP on papers, what value is commonly used?

Thank you!

**Comment by wuhy08** [comment]
Hi @ElectronicElephant 

I believe people tend to use very low threshold to boost up the mAP score. However, it is wise to use higher threshold in application to minimize false positives.

Best,

Haoyu
