### ISSUE TITLE
Missing Ignore thresh

### ISSUE THREAD

**Issue by CuongNguyen218** [westerndigitalcorporation/YOLOv3-in-PyTorch#6]
Hi, @wuhy08 ,
Thanks for your work but i think you missed an parameter. Ignore thresh in original repo is 0.7 and truth thresh is 0.5. Your ignorthresh is 0.5 right ? So it is not same as original
https://github.com/pjreddie/darknet/blob/master/src/yolo_layer.c#L179-183

**Comment by wuhy08** [comment]
Actually Redmon's paper is contradicting his code. In the paper, the ignore_thres is 0.5 and in the code is 0.7.  thruth_thresh is 1. in his code and even not mentioned in the paper. But you are free to change ignore_thres in the config file.
